name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'build.txt'

env:
  IMAGE_NAME: cksac/rust-ml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        IMAGE_VERSION:
          - 25.02-py3

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        environment: build
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          provenance: mode=max
          sbom: true
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.IMAGE_VERSION }}-rust
          push: true
          build-args: IMAGE_VERSION=${{ matrix.IMAGE_VERSION }}
